"""add frequency to habits

Revision ID: b6a91aa5741f
Revises: 
Create Date: 2024-11-14 21:02:50.067630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from schemas import Frequency  # Make sure this import works


# revision identifiers, used by Alembic.
revision: str = 'b6a91aa5741f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    frequency_enum = sa.Enum(Frequency, name='frequency')
    op.add_column('habits', sa.Column('frequency', frequency_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'frequency')
    # ### end Alembic commands ###
